# server.port=8082
# spring.datasource.url = jdbc:mysql://localhost:3306/newspringboot
# spring.datasource.username = root
# spring.datasource.password = KhongCo@123

# spring.jpa.hibernate.ddl-auto = none
# # spring.jpa.hibernate.ddl-auto = create-drop
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

server:
  port: 8082
spring:
    datasource: 
        url: "jdbc:mysql://localhost:3306/newspringboot"
        username: root
        password: KhongCo@123
    jpa: 
        hibernate: 
            ddl-auto: none
        show-sql: true
jwt:
    signerKey: "6NTkXT+FMt8vBvq1xu7Np/Z+TLUTj+oPrWzGmKdJa3CIdtkfv6/pAVovSabww8m6"
    